# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'assignment3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for assignment3
  pod 'Alamofire', '~> 4.5'

  target 'assignment3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'assignment3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
